language: node_js

env:
  - HBASE_VERSION=0.98.5
  - HBASE_VERSION=0.96.2

node_js:
  - "0.10"

before_script:
  - "export HBASE_FILE=hbase-$HBASE_VERSION-hadoop2"
  - "wget http://www.eu.apache.org/dist/hbase/hbase-$HBASE_VERSION/$HBASE_FILE-bin.tar.gz"
  - "tar -xzf $HBASE_FILE-bin.tar.gz"
  - "$HBASE_FILE/bin/start-hbase.sh"
  - "$HBASE_FILE/bin/hbase org.apache.hadoop.hbase.util.RegionSplitter node-hbase-test-table HexStringSplit -c 10 -f cf1"
  - 'echo "alter ''node-hbase-test-table'', {NAME=>''cf1'', VERSIONS => 5}" | JRUBY_OPTS= $HBASE_FILE/bin/hbase shell'
